In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import plotly.graph_objs as go

In [26]:
points=np.array([[0,0,0],[0,1,0],[0,1,1],[0,0,1],
         [1,0,0],[1,1,0],[1,1,1],[1,0,1]],dtype=np.double)

In [27]:
# Define the triangles for each face
triangles = [
    [0, 1, 2],  # Front face
    [3, 2, 0],
    [0, 4, 7],  # Back face
    [3, 0, 7],
    [6, 7, 4],  # Left face
    [6, 5, 4],
    [2, 1, 6],  # Right face
    [5, 6, 1],
    [3, 2, 7],  # Top face
    [6, 2, 7],
    [0, 1, 4],  # Bottom face
    [5, 1, 4],
]

triangles = np.array(triangles)

print(triangles)

[[0 1 2]
 [3 2 0]
 [0 4 7]
 [3 0 7]
 [6 7 4]
 [6 5 4]
 [2 1 6]
 [5 6 1]
 [3 2 7]
 [6 2 7]
 [0 1 4]
 [5 1 4]]


In [28]:
x = []
y = []
z = []
for point in points:
    x.append(point[0])
    y.append(point[1])
    z.append(point[2])

print(x)
print(y)
print(z)


[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0]


In [29]:
%matplotlib widget

In [30]:
# Plotting the mesh lines sometimes helps to make things clearer, not built in with plotly.
# Use this workaround: https://community.plotly.com/t/show-edges-of-the-mesh-in-a-mesh3d-plot/33614/3

def plotMeshPlotly(points,triangles):
    tri_points=points[triangles]
    Xe = []
    Ye = []
    Ze = []
    for T in tri_points:
        Xe.extend([T[k%3][0] for k in range(4)]+[ None])
        Ye.extend([T[k%3][1] for k in range(4)]+[ None])
        Ze.extend([T[k%3][2] for k in range(4)]+[ None])
       
    #define the trace for triangle sides
    lines = go.Scatter3d(
                       x=Xe,
                       y=Ye,
                       z=Ze,
                       mode='lines',
                       name='',
                       line=dict(color= 'rgb(70,70,70)', width=2)) 

    mesh=go.Mesh3d(x=points[:,0],y=points[:,1],z=points[:,2],i=triangles[:,0],j=triangles[:,1],k=triangles[:,2])
    
    fig = go.Figure(data=[mesh,lines],layout={"height":500,"scene":{"aspectratio":{"x":1,"y":1,"z":.4}}})
    fig.show()

In [31]:
points=np.stack([x,y,z],axis=1)
plotMeshPlotly(points, triangles)